"""Market Basket Analytics — Customer Decision Intelligence.

Core analytics modules for market basket analysis, customer segmentation,
demand transference, assortment optimization, pricing elasticity, and more.
"""

from src.analytics.config import (
    DEFAULT_CONFIG,
    AnalyticsConfig,
    get_config,
    set_global_config,
    update_config,
)
from src.analytics.data_quality import (
    DataQualityError,
    DataQualityReport,
    assess_data_quality,
    attach_quality_metadata,
    compute_quality_score,
    filter_data_by_quality,
    generate_quality_summary,
    get_quality_score,
)
from src.analytics.promo.causal import (
    build_promo_causal_panel,
    compute_causal_waterfall,
    estimate_cross_sku_effects,
    estimate_event_study,
    estimate_twfe_promo_effect,
)
from src.analytics.reliability import (
    AnalysisEligibility,
    ReliabilityDimension,
    ReliabilityLevel,
    ReliabilityScore,
    attach_reliability,
    check_analysis_eligibility,
    compute_reliability,
    filter_by_reliability,
)
from src.analytics.schemas import (
    ABC_CLASSES,
    ADDON_RECS,
    # Co-purchase / add-on
    AFFINITY_PAIRS,
    ASSORTMENT_EFFICIENCY,
    ASSORTMENT_EVALUATION,
    ASSORTMENT_SCENARIO,
    # Assortment
    ASSORTMENT_SOLUTION,
    BASKET_COMPOSITION,
    BASKET_OVER_TIME,
    # Basket metrics
    BASKET_PENETRATION,
    BEHAVIORAL_FEATURES,
    BEHAVIORAL_SEGMENTS,
    # Category / performance
    CATEGORY_KPIS,
    CATEGORY_MANAGER_SCORECARD,
    # Promotional
    CATEGORY_PROMO_TIMELINE,
    CATEGORY_SCORECARD,
    CATEGORY_SWITCHING,
    CATEGORY_TREND,
    CAUSAL_UPLIFT,
    CDT_ASSIGNMENTS,
    # CDT
    CDT_ATTRIBUTES,
    CDT_COMMUNITY,
    CDT_OPTIMAL_K,
    CDT_QUALITY,
    CDT_TREE_NODES,
    CDT_TREE_PRODUCTS,
    CDT_TREE_SCORE,
    CDT_VALIDATION,
    CLUSTER_QUALITY,
    CLUSTER_STABILITY,
    CLV_CUSTOMER,
    CLV_DIAGNOSTICS,
    # CLV
    CLV_PREDICTIONS,
    COHORT_DECAY,
    COHORT_LTV,
    # Cohort
    COHORT_RETENTION,
    COHORT_SIZES,
    CROSS_ELASTICITY,
    CUSTOMER_ENTROPY,
    # Choice model
    CUSTOMER_FEATURES,
    DELIST_IMPACT,
    # Transference
    DEMAND_TRANSFERENCE,
    # Pricing
    ELASTICITY,
    # Rules / association
    FREQUENT_ITEMSETS,
    HIERARCHICAL_ELASTICITY,
    HIGH_VALUE_SWITCHING,
    INFERRED_CATEGORIES,
    IPT_CV,
    IV_ELASTICITY,
    KVI_SCORES,
    LIFECYCLE,
    LOYALTY_METRICS,
    MODEL_METRICS,
    NODE_DELIST_IMPACT,
    POP_COMPARISON,
    PRICE_CURVE_1D,
    PRICE_CURVE_MULTI,
    PRODUCT_METRICS,
    PRODUCT_VELOCITY,
    PROMO_BASELINE,
    PROMO_HALO,
    PROMO_LIFT,
    PROMO_PERIODS,
    PROMO_ROI,
    PROMO_TIMING_DOW,
    PROMO_TIMING_MONTH,
    PROMO_WATERFALL,
    QINI_CURVE,
    RDD_ELASTICITY,
    RECOVERY_HHI,
    REPEAT_RATE,
    # Segmentation
    RFM_FEATURES,
    RFM_SEGMENTS,
    RULES,
    RULES_TABLE,
    SDP_SCORES,
    SECOND_PURCHASE,
    SKU_RATIONALIZATION,
    SURVIVAL_DIAGNOSTICS,
    SURVIVAL_PREDICTIONS,
    # Switching
    SWITCHING_MATRIX,
    # Switching (new contracts)
    SWITCHING_MATRIX_CI,
    SWITCHING_OPPORTUNITY,
    SWITCHING_SUBSTITUTION,
    SYNTHETIC_CONTROL,
    # Core
    TRANSACTIONS,
    TRANSFERENCE_CI,
    TREE_RULES,
    UPLIFT_METRICS,
    UPLIFT_PROPENSITY,
    UPLIFT_SCORES,
    VALUE_BASED_SEGMENTS,
    XYZ_CLASSES,
    YOY_COMPARISON,
    DataContract,
    EmptyResult,
    SchemaError,
    ValueValidator,
    check,
    contract,
    is_empty_result,
    make_empty_result,
    validate_referential_integrity,
)
from src.analytics.statistical_contract import (
    ASSORTMENT_CONTRACT,
    CLV_CONTRACT,
    CONTRACT_REGISTRY,
    ELASTICITY_CONTRACT,
    StatisticalAssumption,
    StatisticalClaimType,
    StatisticalContract,
    attach_contract,
    get_contract,
    register_contract,
    validate_against_contract,
)
from src.analytics.validation import (
    ValidationHarness,
    assert_validation,
    export_baseline,
    run_validation,
)

# Package version
__version__ = "2.0.0"

# Public API - module-level imports for direct access
from src.analytics import (
    assortment,
    basket_metrics,
    category,
    cdt,
    choice_model,
    clv,
    cohort,
    copurchase,
    data,
    performance,
    pricing,
    promo,
    rules,
    segmentation,
    switching,
    transference,
)

__all__ = [
    # Config
    "AnalyticsConfig",
    "DEFAULT_CONFIG",
    "get_config",
    "update_config",
    "set_global_config",
    # Validation
    "ValidationHarness",
    "run_validation",
    "export_baseline",
    "assert_validation",
    # Reliability
    "ReliabilityLevel",
    "ReliabilityDimension",
    "ReliabilityScore",
    "AnalysisEligibility",
    "compute_reliability",
    "check_analysis_eligibility",
    "attach_reliability",
    "filter_by_reliability",
    # Data Quality
    "DataQualityReport",
    "DataQualityError",
    "assess_data_quality",
    "filter_data_by_quality",
    "generate_quality_summary",
    "compute_quality_score",
    "attach_quality_metadata",
    "get_quality_score",
    # Statistical Contracts
    "StatisticalClaimType",
    "ReliabilityLevel",
    "StatisticalAssumption",
    "StatisticalContract",
    "ELASTICITY_CONTRACT",
    "CLV_CONTRACT",
    "ASSORTMENT_CONTRACT",
    "attach_contract",
    "get_contract",
    "register_contract",
    "validate_against_contract",
    "CONTRACT_REGISTRY",
    # Causal Promo
    "build_promo_causal_panel",
    "estimate_twfe_promo_effect",
    "estimate_event_study",
    "estimate_cross_sku_effects",
    "compute_causal_waterfall",
    # Modules (access via src.analytics.<module>)
    "assortment",
    "basket_metrics",
    "category",
    "cdt",
    "choice_model",
    "clv",
    "cohort",
    "copurchase",
    "data",
    "performance",
    "pricing",
    "promo",
    "rules",
    "segmentation",
    "switching",
    "transference",
    # Schemas (contracts)
    "check",
    "contract",
    "SchemaError",
    "DataContract",
    "ValueValidator",
    "EmptyResult",
    "is_empty_result",
    "make_empty_result",
    "validate_referential_integrity",
    "TRANSACTIONS",
    "FREQUENT_ITEMSETS",
    "RULES",
    "RULES_TABLE",
    "AFFINITY_PAIRS",
    "ADDON_RECS",
    "SWITCHING_MATRIX",
    "LOYALTY_METRICS",
    "CATEGORY_SWITCHING",
    "BASKET_PENETRATION",
    "BASKET_OVER_TIME",
    "BASKET_COMPOSITION",
    "CUSTOMER_ENTROPY",
    "IPT_CV",
    "COHORT_RETENTION",
    "COHORT_SIZES",
    "POP_COMPARISON",
    "YOY_COMPARISON",
    "COHORT_LTV",
    "COHORT_DECAY",
    "CATEGORY_KPIS",
    "CATEGORY_SCORECARD",
    "CATEGORY_MANAGER_SCORECARD",
    "CATEGORY_TREND",
    "ASSORTMENT_EFFICIENCY",
    "INFERRED_CATEGORIES",
    "PRODUCT_METRICS",
    "ABC_CLASSES",
    "XYZ_CLASSES",
    "LIFECYCLE",
    "PRODUCT_VELOCITY",
    "REPEAT_RATE",
    "SECOND_PURCHASE",
    "SKU_RATIONALIZATION",
    "CUSTOMER_FEATURES",
    "MODEL_METRICS",
    "TREE_RULES",
    "CATEGORY_PROMO_TIMELINE",
    "PROMO_PERIODS",
    "PROMO_BASELINE",
    "PROMO_LIFT",
    "PROMO_WATERFALL",
    "PROMO_ROI",
    "PROMO_TIMING_DOW",
    "PROMO_TIMING_MONTH",
    "PROMO_HALO",
    "UPLIFT_PROPENSITY",
    "UPLIFT_METRICS",
    "UPLIFT_SCORES",
    "QINI_CURVE",
    "CLV_PREDICTIONS",
    "CLV_DIAGNOSTICS",
    "CLV_CUSTOMER",
    "DEMAND_TRANSFERENCE",
    "SDP_SCORES",
    "DELIST_IMPACT",
    "NODE_DELIST_IMPACT",
    "CROSS_ELASTICITY",
    "RECOVERY_HHI",
    "TRANSFERENCE_CI",
    "SWITCHING_MATRIX_CI",
    "SWITCHING_SUBSTITUTION",
    "HIGH_VALUE_SWITCHING",
    "SWITCHING_OPPORTUNITY",
    "ASSORTMENT_SOLUTION",
    "ASSORTMENT_SCENARIO",
    "ASSORTMENT_EVALUATION",
    "CDT_ATTRIBUTES",
    "CDT_ASSIGNMENTS",
    "CDT_QUALITY",
    "CDT_OPTIMAL_K",
    "CDT_COMMUNITY",
    "CDT_TREE_NODES",
    "CDT_TREE_PRODUCTS",
    "CDT_VALIDATION",
    "CDT_TREE_SCORE",
    "RFM_FEATURES",
    "RFM_SEGMENTS",
    "BEHAVIORAL_FEATURES",
    "BEHAVIORAL_SEGMENTS",
    "SURVIVAL_PREDICTIONS",
    "SURVIVAL_DIAGNOSTICS",
    "VALUE_BASED_SEGMENTS",
    "CLUSTER_QUALITY",
    "CLUSTER_STABILITY",
    "ELASTICITY",
    "HIERARCHICAL_ELASTICITY",
    "CROSS_ELASTICITY",
    "KVI_SCORES",
    "PRICE_CURVE_1D",
    "PRICE_CURVE_MULTI",
    "IV_ELASTICITY",
    "RDD_ELASTICITY",
    "SYNTHETIC_CONTROL",
    "CAUSAL_UPLIFT",
]
