"""Market Basket Analytics — Customer Decision Intelligence.

Core analytics modules for market basket analysis, customer segmentation,
demand transference, assortment optimization, pricing elasticity, and more.
"""

from src.analytics.config import AnalyticsConfig, DEFAULT_CONFIG, get_config, update_config
from src.analytics.schemas import (
    check,
    contract,
    SchemaError,
    DataContract,
    ValueValidator,
    EmptyResult,
    is_empty_result,
    make_empty_result,
    validate_referential_integrity,
    # Core
    TRANSACTIONS,
    # Rules / association
    FREQUENT_ITEMSETS,
    RULES,
    RULES_TABLE,
    # Co-purchase / add-on
    AFFINITY_PAIRS,
    ADDON_RECS,
    # Switching
    SWITCHING_MATRIX,
    LOYALTY_METRICS,
    # Basket metrics
    BASKET_PENETRATION,
    BASKET_OVER_TIME,
    BASKET_COMPOSITION,
    CUSTOMER_ENTROPY,
    IPT_CV,
    # Cohort
    COHORT_RETENTION,
    COHORT_SIZES,
    POP_COMPARISON,
    YOY_COMPARISON,
    COHORT_LTV,
    COHORT_DECAY,
    # Category / performance
    CATEGORY_KPIS,
    CATEGORY_SCORECARD,
    INFERRED_CATEGORIES,
    PRODUCT_METRICS,
    ABC_CLASSES,
    XYZ_CLASSES,
    LIFECYCLE,
    PRODUCT_VELOCITY,
    REPEAT_RATE,
    SECOND_PURCHASE,
    SKU_RATIONALIZATION,
    # Choice model
    CUSTOMER_FEATURES,
    MODEL_METRICS,
    TREE_RULES,
    # Promotional
    PROMO_PERIODS,
    PROMO_BASELINE,
    PROMO_LIFT,
    PROMO_WATERFALL,
    PROMO_ROI,
    PROMO_TIMING_DOW,
    PROMO_TIMING_MONTH,
    PROMO_HALO,
    UPLIFT_PROPENSITY,
    UPLIFT_METRICS,
    UPLIFT_SCORES,
    QINI_CURVE,
    # CLV
    CLV_PREDICTIONS,
    CLV_DIAGNOSTICS,
    CLV_CUSTOMER,
    # Transference
    DEMAND_TRANSFERENCE,
    SDP_SCORES,
    DELIST_IMPACT,
    NODE_DELIST_IMPACT,
    CROSS_ELASTICITY,
    RECOVERY_HHI,
    TRANSFERENCE_CI,
    # Assortment
    ASSORTMENT_SOLUTION,
    ASSORTMENT_SCENARIO,
    ASSORTMENT_EVALUATION,
    # CDT
    CDT_ATTRIBUTES,
    CDT_ASSIGNMENTS,
    CDT_QUALITY,
    CDT_OPTIMAL_K,
    CDT_COMMUNITY,
    CDT_TREE_NODES,
    CDT_TREE_PRODUCTS,
    CDT_VALIDATION,
    CDT_TREE_SCORE,
    # Segmentation
    RFM_FEATURES,
    RFM_SEGMENTS,
    BEHAVIORAL_FEATURES,
    BEHAVIORAL_SEGMENTS,
    SURVIVAL_PREDICTIONS,
    SURVIVAL_DIAGNOSTICS,
    VALUE_BASED_SEGMENTS,
    CLUSTER_QUALITY,
    CLUSTER_STABILITY,
    # Pricing
    ELASTICITY,
    HIERARCHICAL_ELASTICITY,
    CROSS_ELASTICITY,
    KVI_SCORES,
    PRICE_CURVE_1D,
    PRICE_CURVE_MULTI,
    IV_ELASTICITY,
    RDD_ELASTICITY,
    SYNTHETIC_CONTROL,
    CAUSAL_UPLIFT,
)
from src.analytics.validation import ValidationHarness, run_validation, export_baseline, assert_validation

# Package version
__version__ = "2.0.0"

# Public API - module-level imports for direct access
from src.analytics import (
    assortment,
    basket_metrics,
    category,
    cdt,
    choice_model,
    clv,
    cohort,
    copurchase,
    data,
    performance,
    pricing,
    promo,
    rules,
    segmentation,
    switching,
    transference,
)

__all__ = [
    # Config
    "AnalyticsConfig",
    "DEFAULT_CONFIG",
    "get_config",
    "update_config",
    # Validation
    "ValidationHarness",
    "run_validation",
    "export_baseline",
    "assert_validation",
    # Modules (access via src.analytics.<module>)
    "assortment",
    "basket_metrics",
    "category",
    "cdt",
    "choice_model",
    "clv",
    "cohort",
    "copurchase",
    "data",
    "performance",
    "pricing",
    "promo",
    "rules",
    "segmentation",
    "switching",
    "transference",
    # Schemas (contracts)
    "check",
    "contract",
    "SchemaError",
    "DataContract",
    "ValueValidator",
    "EmptyResult",
    "is_empty_result",
    "make_empty_result",
    "validate_referential_integrity",
    "TRANSACTIONS",
    "FREQUENT_ITEMSETS",
    "RULES",
    "RULES_TABLE",
    "AFFINITY_PAIRS",
    "ADDON_RECS",
    "SWITCHING_MATRIX",
    "LOYALTY_METRICS",
    "BASKET_PENETRATION",
    "BASKET_OVER_TIME",
    "BASKET_COMPOSITION",
    "CUSTOMER_ENTROPY",
    "IPT_CV",
    "COHORT_RETENTION",
    "COHORT_SIZES",
    "POP_COMPARISON",
    "YOY_COMPARISON",
    "COHORT_LTV",
    "COHORT_DECAY",
    "CATEGORY_KPIS",
    "CATEGORY_SCORECARD",
    "INFERRED_CATEGORIES",
    "PRODUCT_METRICS",
    "ABC_CLASSES",
    "XYZ_CLASSES",
    "LIFECYCLE",
    "PRODUCT_VELOCITY",
    "REPEAT_RATE",
    "SECOND_PURCHASE",
    "SKU_RATIONALIZATION",
    "CUSTOMER_FEATURES",
    "MODEL_METRICS",
    "TREE_RULES",
    "PROMO_PERIODS",
    "PROMO_BASELINE",
    "PROMO_LIFT",
    "PROMO_WATERFALL",
    "PROMO_ROI",
    "PROMO_TIMING_DOW",
    "PROMO_TIMING_MONTH",
    "PROMO_HALO",
    "UPLIFT_PROPENSITY",
    "UPLIFT_METRICS",
    "UPLIFT_SCORES",
    "QINI_CURVE",
    "CLV_PREDICTIONS",
    "CLV_DIAGNOSTICS",
    "CLV_CUSTOMER",
    "DEMAND_TRANSFERENCE",
    "SDP_SCORES",
    "DELIST_IMPACT",
    "NODE_DELIST_IMPACT",
    "CROSS_ELASTICITY",
    "RECOVERY_HHI",
    "TRANSFERENCE_CI",
    "ASSORTMENT_SOLUTION",
    "ASSORTMENT_SCENARIO",
    "ASSORTMENT_EVALUATION",
    "CDT_ATTRIBUTES",
    "CDT_ASSIGNMENTS",
    "CDT_QUALITY",
    "CDT_OPTIMAL_K",
    "CDT_COMMUNITY",
    "CDT_TREE_NODES",
    "CDT_TREE_PRODUCTS",
    "CDT_VALIDATION",
    "CDT_TREE_SCORE",
    "RFM_FEATURES",
    "RFM_SEGMENTS",
    "BEHAVIORAL_FEATURES",
    "BEHAVIORAL_SEGMENTS",
    "SURVIVAL_PREDICTIONS",
    "SURVIVAL_DIAGNOSTICS",
    "VALUE_BASED_SEGMENTS",
    "CLUSTER_QUALITY",
    "CLUSTER_STABILITY",
    "ELASTICITY",
    "HIERARCHICAL_ELASTICITY",
    "CROSS_ELASTICITY",
    "KVI_SCORES",
    "PRICE_CURVE_1D",
    "PRICE_CURVE_MULTI",
    "IV_ELASTICITY",
    "RDD_ELASTICITY",
    "SYNTHETIC_CONTROL",
    "CAUSAL_UPLIFT",
]